version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
